### ISSUE TITLE
Just FYI "urllib3" appears twice in pdm.lock

### ISSUE THREAD

**Issue by holta** [chapmanjacobd/library#29]
No doubt harmless! ✅

But just FYI if in future dependencies ever need to be organized or reconciled... 💯

https://github.com/chapmanjacobd/library/blob/8e1d57c2c80cfd1180658fc940cebcf60daecfe0/pdm.lock#L2322-L2345

**Comment by chapmanjacobd** [comment]
yeah I'm not sure why that happens. maybe because urllib3[socks] depends on urllib3.

when upgrading to py3.12 I had to do `pip install --upgrade --ignore-installed urllib3 requests` due to `six` bundling (urllib3.packages.six) but I think that is completely unrelated

This file is created by `pdm` so it might be worth opening an issue there.
