### ISSUE TITLE
What is "xk"?

### ISSUE THREAD

**Issue by yyolk** [chapmanjacobd/library#30]
I just stumbled onto this repository today and think it's pretty cool! 

Please excuse my ignorance, what does "**xk**" stand for in the repository description? As in, "xk media library".

I spent a few minutes searching but I think it might be a code name or old project name. 

I wanted to see if I was missing something obvious and thought maybe this was part of a larger ecosystem of stuff, but plan to dive into trying this out nonetheless, as the "autotainment" idea resonates with me.

Thank you!

**Comment by chapmanjacobd** [comment]
Interesting question!

- Country code (ISO 3166) of the [Republic of Kosovo](https://en.wikipedia.org/wiki/Kosovo)
- XKCD?
    -  [What does XKCD stand for?](https://xkcd.com/about/)
    It's not actually an acronym. It's just a word with no phonetic pronunciation -- a treasured and carefully-guarded point in the space of four-character strings.
- [crosswalk](https://unli.xyz/c/): cross is **x**, walk ends with **k**. A defunct crowdfunding project but [the wiki](https://unli.xyz/c/wiki.html#CrosswalkWiki) might have some interesting thoughts. [YC](https://unli.xyz/p/2017/YC_alt.cinema.pdf) somewhat related.

I'm not sure exactly why I felt "crosswalk" needed to have a shortened name but I put those two letters together without thinking about Kosovo or Randall Munroe. But I resurrected that acronym while trying to find a short pypi package name. In some ways xk is my name because it is my username on the computer.

However, I am [in the process of](https://github.com/pypi/support/issues/3100) renaming the package to library once that becomes available.

**Comment by yyolk** [comment]
Thank you for the detailed answer :)

I really hope you get the namespace!
