### ISSUE TITLE
yt-dlp is not installed

### ISSUE THREAD

**Issue by deldesir** [chapmanjacobd/library#45]
**Describe the bug**
yt-dlp is not installed anymore.

**Expected behavior**
yt-dlp should be installed like before the renaming (with `pipx install xklb`)

**To Reproduce**
```
pipx install library
yt-dlp --version
```

**Comment by chapmanjacobd** [comment]
I don't think this behavior has changed since previous versions.

`pipx` does not expose dependency programs. Try with `pip` (or use `pipx` to install yt_dlp. But, it won't be the same yt-dlp that library uses. You would need to inject the updated dependency if you wanted to update yt-dlp inside of the place that `pipx` installs `library`)

Actually, I don't really recommend `pipx` or `venv`. It makes things more complicated. I've never personally had issues with conflicting dependencies except on systems that target old versions of software, like CentOS

**Comment by deldesir** [comment]
Thanks for the explanation. I confirm yt-dlp is installed during library installation.
```
.local/share/pipx/venvs/library/bin/yt-dlp --version
```
